name: candle
description: "Accessible Navigation App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.11+22

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_blue_plus: ^1.30.5
  flutter_compass: ^0.8.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_map: ^6.1.0
  flutter_markdown: ^0.6.18+3
  flutter_screen_wake: ^1.0.2
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  get: ^4.6.6
  google_geocoding_api: ^1.4.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  image: ^3.2.0
  intl: any
  latlong2: ^0.9.0
  location: ^5.0.3
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  provider: ^6.1.1
  sensors: ^2.0.3
 
  simple_shadow: ^0.3.1
  speech_to_text: ^6.5.1
  sqflite: ^2.3.0
  string_similarity: ^2.0.0
  url_launcher: ^6.2.4
  uuid: ^4.2.2
  vibration: ^1.8.4
  geolocator: ^10.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  xml: ^6.5.0
  google_sign_in: ^6.2.1
  receive_sharing_intent: ^1.6.6
  share_extend: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/images/
    - assets/
