name: candle
description: "Accessible Navigation App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_blue_plus: ^1.30.5
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: any
  location: ^5.0.3
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  flutter_svg: ^2.0.9
  flutter_compass: ^0.8.0
  permission_handler: ^11.1.0
  simple_shadow: ^0.3.1
  speech_to_text: ^6.5.1
  latlong2: ^0.9.0
  vibration: ^1.8.4
  flutter_screen_wake: ^1.0.2
  provider: ^6.1.1
  string_similarity: ^2.0.0
  flutter_google_maps_webservices: ^1.1.1
  google_maps_flutter: ^2.5.0
  google_geocoding_api: ^1.4.1
  uuid: ^4.2.2
  collection: ^1.18.0
  logger: ^2.0.2+1
  share: ^2.0.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # Use the latest version
  test: ^1.24.9

flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - assets/images/

