name: candle
description: "Accessible Navigation App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+6

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+7
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.30.5
  flutter_compass: ^0.8.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  flutter_screen_wake: ^1.0.2
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_vision: ^1.1.4
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_geocoding_api: ^1.4.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  image: ^3.2.0
  intl: any
  latlong2: ^0.9.0
  location: ^5.0.3
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  share: ^2.0.4
  simple_shadow: ^0.3.1
  speech_to_text: ^6.5.1
  sqflite: ^2.3.0
  string_similarity: ^2.0.0
  url_launcher: ^6.2.2
  uuid: ^4.2.2
  vibration: ^1.8.4

dev_dependencies:
  flutter_launcher_icons: "^0.11.0" # Use the latest version
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/images/
    - assets/
