name: candle
description: "Accessible Navigation App"
publish_to: 'none'
version: 1.4.5+42

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.8.1
  collection: ^1.19.1
  device_info_plus: ^13.2.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_compass: ^0.8.1
  flutter_map: ^8.3.2
  flutter_markdown_plus: ^1.0.12
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.3.0
  geolocator: ^14.0.1
  html: ^0.15.7
  http: ^1.6.0
  intl: ^0.20.2
  latlong2: ^0.10.1
  logger: ^2.8.0
  package_info_plus: ^10.2.1
  path: ^1.9.1
  path_provider: ^2.1.6
  permission_handler: ^13.0.2
  provider: ^6.1.5+1
  receive_sharing_intent: ^1.9.0
  rxdart: ^0.28.0
  sensors_plus: ^7.1.0
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  simple_shadow: ^0.3.1
  speech_to_text: ^7.5.0
  sqflite: ^2.4.4
  url_launcher: ^6.3.2
  vibration: ^3.2.1
  wakelock_plus: ^1.8.1
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1
  flutter_secure_storage: ^11.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
