#:import SayButton controls.say_button.SayButton
#:import Header controls.header.Header
#:import BorderWidget controls.border_widget.BorderWidget
#:import _ utils.i18n._

<Confirm>:

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Header:
            id: header
            text: _('Bestätigung')
            say: _('Bitte bestätigen Sie')


        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 1  # Take up the remaining space
            spacing: 10
            padding: 10

            # Spacer to push SayButtons to the top
            Widget:
                size_hint_y: 1


        BoxLayout:
            size_hint_y: None
            height: '64dp'
            spacing: 10

            SayButton:
                text: _('Bestätigen')
                say: _('Bestätigen')
                vibrate: 2
                action: root.confirm
                halign: 'center'

            SayButton:
                text: _('Abbruch')
                say: _('Abbruch')
                vibrate: 2
                action: root.cancel
                halign: 'center'
