#:import SayButton controls.say_button.SayButton
#:import Header controls.header.Header
#:import BorderWidget controls.border_widget.BorderWidget
#:import Swipe controls.swipe_box.Swipe
#:import _ utils.i18n._

<Navigation>:

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Header:
            id: header
            text: _('Navigation')
            say: _('Untermenu: Navigation')

        Swipe:
            orientation: 'vertical'
            size_hint_y: 1  # Take up the remaining space
            spacing: 10
            padding: 10
            swipe_right: root.back

            SayButton:
                text: _('Standort speichern')
                say: _('Ihren aktuellen Standort speichern')
                action: root.save_location
                size_hint_y: 1

            SayButton:
                text: _('Orte')
                say: _('Gespeicherte Orte')
                action: app.navigate_to_pois
                size_hint_y: 1

            SayButton:
                text: _('Strecken')
                say: _('Aufgezeichnete Strecken')
                size_hint_y: 1

            SayButton:
                text: _('Testdaten')
                say: _('Testdaten einfügen')
                size_hint_y: 1
                action: root.testdata

            BorderWidget:
                size_hint_y: 1
            BorderWidget:
                size_hint_y: 1
            BorderWidget:
                size_hint_y: 1
            BorderWidget:
                size_hint_y: 1
            BorderWidget:
                size_hint_y: 1
            BorderWidget:
                size_hint_y: 1
            BorderWidget:
                size_hint_y: 1

        BoxLayout:
            size_hint_y: None
            height: '64dp'
            spacing: 10

            SayButton:
                text: _('Zurück')
                say: _('Zurück ins Hauptmenü')
                vibrate: 2
                action: root.back
                halign: 'center'

            SayButton:
                text: _('Hilfe')
                say: _('Hilfe')
                vibrate: 2
                halign: 'center'



