#:import SayButton controls.say_button.SayButton
#:import Header controls.header.Header
#:import BorderWidget controls.border_widget.BorderWidget
#:import Swipe controls.swipe_box.Swipe
#:import _ utils.i18n._
#:import MapView kivy_garden.mapview.MapView

<PoiRouting>:

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Header:
            id: header
            text: _('Ort Details')
            say: _('Untermenu: Ort Details')

        Swipe:
            orientation: 'vertical'
            size_hint_y: 1
            spacing: 10
            padding: 10
            swipe_right: root.back

            SayButton:
                text: _('Anhalten')
                say: _('Navigation Pausieren')
                size_hint_y: 1
                action: root.navigation_pause

            SayButton:
                text: _('Route anzeigen')
                say: _('Route anzeigen')
                size_hint_y: 1
                action: root.navigation_show

            SayButton:
                text: _('Ziel ändern')
                say: _('Ziel ändern')
                size_hint_y: 1
                action: root.navigation_change

            SayButton:
                text: _('Stopp')
                say: _('Stopp der Navigation')
                size_hint_y: 1
                action: root.navigation_stop

            MapView:
                id: mapview
                zoom: 20
                lat: 37.7749  # Initial latitude
                lon: -122.4194  # Initial longitude
                size_hint_y: 6

        BoxLayout:
            size_hint_y: None
            height: '64dp'
            spacing: 10

            SayButton:
                text: _('Zurück')
                say: _('Zurück zur Orte')
                vibrate: 2
                action: root.back
                halign: 'center'

            SayButton:
                text: _('Hilfe')
                say: _('Hilfe')
                vibrate: 2
                halign: 'center'



