#:import SayButton controls.say_button.SayButton

<RecordingScreen>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            text:"Recording"

        SayButton:
            say: "Start Recording"
            text: "Start Recording"
            on_release: app.custom_action


        SayButton:
            say: "Zurück"
            text: "Zurück"
            on_release: root.back

