<SayButton>:
    orientation: "vertical"
    size_hint_y: None
    height: dp(64) 

    BoxLayout:

        CustomButton:
            text: root.text
            size_hint_x: 4
            on_release: root.on_button_release
            font_size: '20sp' 
            bold: True
            halign: 'left'
            valign: 'middle'
            text_size: self.width - dp(20), None
            padding: dp(10), dp(0)
