// Generates the short texts of the app from lib/l10n/arb/short/app_<lang>_short.arb:
// lib/l10n/gen/short_localizations.dart picks the language, lib/l10n/gen/short_localizations_<lang>.dart
// holds its texts (the same layout as Flutter's generated app_localizations*.dart).
//
//   dart run tool/gen_short_l10n.dart
//
// Each short file holds only the texts that have a shorter version (for experienced
// screen reader users). The generated classes extend the generated AppLocalizations of
// that language and override just those texts; signatures come from
// lib/l10n/gen/app_localizations.dart, so they always match.
import 'dart:convert';
import 'dart:io';

const _header = """// GENERATED by tool/gen_short_l10n.dart from lib/l10n/arb/short/*.arb - do not edit.
// The names are the ones of the generated AppLocalizations.
// ignore_for_file: non_constant_identifier_names, unnecessary_string_interpolations
""";

void main() {
  for (final MapEntry(key: path, value: content) in generate().entries) {
    File(path).writeAsStringSync(content);
    stdout.writeln('wrote $path');
  }
}

/// The generated files, path to content.
Map<String, String> generate() {
  final signatures = _signatures(File('lib/l10n/gen/app_localizations.dart').readAsStringSync());
  final pattern = RegExp(r'app_(\w+)_short\.arb$');
  final files = {
    for (final file in Directory('lib/l10n/arb/short').listSync().whereType<File>())
      if (pattern.firstMatch(file.path) case final match?) match.group(1)!: file,
  };
  final languages = files.keys.toList()..sort();

  final index = StringBuffer()
    ..writeln(_header)
    ..writeln("import 'package:candle/l10n/gen/app_localizations.dart';");
  for (final language in languages) {
    index.writeln("import 'package:candle/l10n/gen/short_localizations_$language.dart';");
  }
  index
    ..writeln()
    ..writeln('/// The short texts of [languageCode], or null if there are none.')
    ..writeln('AppLocalizations? shortLocalizations(String languageCode) => switch (languageCode) {');
  for (final language in languages) {
    index.writeln("      '$language' => ${_className(language)}(),");
  }
  index
    ..writeln('      _ => null,')
    ..writeln('    };');

  return {
    'lib/l10n/gen/short_localizations.dart': index.toString(),
    for (final language in languages)
      'lib/l10n/gen/short_localizations_$language.dart':
          _languageFile(language, files[language]!, signatures),
  };
}

String _languageFile(String language, File file, Map<String, _Signature> signatures) {
  final texts = (jsonDecode(file.readAsStringSync()) as Map<String, dynamic>)
    ..removeWhere((key, _) => key.startsWith('@'));
  final out = StringBuffer()
    ..writeln(_header)
    ..writeln("import 'package:candle/l10n/gen/app_localizations_$language.dart';")
    ..writeln()
    ..writeln('class ${_className(language)} extends ${_baseName(language)} {');
  for (final MapEntry(:key, :value) in texts.entries) {
    final signature = signatures[key];
    if (signature == null) throw StateError('${file.path}: "$key" is no text of the app');
    for (final placeholder in RegExp(r'\{(\w+)\}').allMatches(value as String)) {
      if (!signature.parameters.contains(placeholder.group(1))) {
        throw StateError('${file.path}: "$key" has no placeholder {${placeholder.group(1)}}');
      }
    }
    out
      ..writeln('  @override')
      ..writeln(signature.isGetter
          ? '  String get $key => ${_dartString(value)};'
          : '  String $key(${signature.declaration}) => ${_dartString(value)};');
  }
  out.writeln('}');
  return out.toString();
}

String _baseName(String language) =>
    'AppLocalizations${language[0].toUpperCase()}${language.substring(1)}';

String _className(String language) => '${_baseName(language)}Short';

/// Turns "{degree} Grad links" into '$degree Grad links'.
String _dartString(String text) {
  final escaped = text.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
  // braces only where the next character would continue the name
  final interpolated = escaped.replaceAllMapped(
    RegExp(r'\{(\w+)\}(?=(\w?))'),
    (m) => m.group(2)!.isEmpty ? '\$${m.group(1)}' : '\${${m.group(1)}}',
  );
  return "'$interpolated'";
}

class _Signature {
  _Signature.getter() : isGetter = true, declaration = '', parameters = const [];
  _Signature.method(this.declaration)
      : isGetter = false,
        parameters = [
          for (final parameter in declaration.split(',').where((p) => p.trim().isNotEmpty))
            parameter.trim().split(RegExp(r'\s+')).last,
        ];

  final bool isGetter;

  /// Parameter list of a method, e.g. "int degree".
  final String declaration;
  final List<String> parameters;
}

/// The texts declared in the generated abstract AppLocalizations class.
Map<String, _Signature> _signatures(String source) => {
      for (final m in RegExp(r'^  String get (\w+);', multiLine: true).allMatches(source))
        m.group(1)!: _Signature.getter(),
      for (final m in RegExp(r'^  String (\w+)\(([^)]*)\);', multiLine: true).allMatches(source))
        m.group(1)!: _Signature.method(m.group(2)!),
    };
